import Phaser from 'phaser';
import { Player } from '../entities/Player';

export class CommunityMeterManager {
  private player: Player;
  public meterValue: number = 75; // 0 to 100
  public isCrisis: boolean = false;
  private crisisDebuffApplied: boolean = false;
  public isHealthy: boolean = false;
  private healthyBuffApplied: boolean = false;

  constructor(_scene: Phaser.Scene, player: Player) {
    this.player = player;
  }

  public update(dt: number, activeEnemyCount: number, isBossActive: boolean = false): void {
    const dtSec = dt / 1000;

    // 1. Continuous digital pollution from roaming negative phenomena
    // Each living mob creates ambient background toxicity
    const mobPollution = activeEnemyCount * 0.035 * dtSec;
    const bossPollution = isBossActive ? 0.45 * dtSec : 0;
    const totalPollution = mobPollution + bossPollution;

    // 2. Active purification generated by player's Build (Xây) power
    const buildRecovery = (this.player.values.build * 0.12 + this.player.stats.buildPower * 0.02) * dtSec;

    // Net balance
    this.modify(buildRecovery - totalPollution);

    // 3. Healthy State Buff (> 70%): Rewarding players for maintaining a clean cyberspace
    if (this.meterValue > 70) {
      if (!this.healthyBuffApplied) {
        this.healthyBuffApplied = true;
        this.isHealthy = true;
        this.player.stats.moveSpeed *= 1.08; // +8% speed bonus
      }
    } else {
      if (this.healthyBuffApplied) {
        this.healthyBuffApplied = false;
        this.isHealthy = false;
        this.player.stats.moveSpeed /= 1.08;
      }
    }

    // 4. Crisis State Debuff (<= 0%): Severe debuff when cyberspace collapses
    if (this.meterValue <= 0 && !this.isCrisis) {
      this.triggerCrisis();
    } else if (this.meterValue > 25 && this.isCrisis) {
      this.resolveCrisis();
    }
  }

  public modify(delta: number): void {
    this.meterValue = Phaser.Math.Clamp(this.meterValue + delta, 0, 100);
  }

  private triggerCrisis(): void {
    this.isCrisis = true;
    if (!this.crisisDebuffApplied) {
      this.crisisDebuffApplied = true;
      // Debuff: -25% damage, -20% speed per GDD
      this.player.stats.damage *= 0.75;
      this.player.stats.moveSpeed *= 0.8;
    }
  }

  private resolveCrisis(): void {
    this.isCrisis = false;
    if (this.crisisDebuffApplied) {
      this.crisisDebuffApplied = false;
      this.player.stats.damage /= 0.75;
      this.player.stats.moveSpeed /= 0.8;
    }
  }
}
